### ISSUE TITLE
write a "turn-key" script to build and run clams-galaxy appliance instance

### ISSUE THREAD

**Issue by keighrim** [clamsproject/appliance#2]
Here's a step-by-step tasks that this "turn-key" script to carry out. 

```
# script requires a config file, that can be written in json, yaml, or any other human friendly data format that we decide to use 

# download apps specified in config
# for app in apps: 
    # build app docker image 
        # if dockerfile exsits? use it
        # no dockerfile? use some default one (preferably shipped along with this script)
            # when given no dockerfile, we need some kind of default entrypoint (e.g. run.py) 
    # run the image to start the app as a webservice
    # create tool.xml files from appmetadata 
        # retrieved from the running webapp by calling POST on the docker container to get appmetadata
    # add this new tool to tool_conf.xml on-the-fly
        # need to keep track of tools to be deployed in a single appliance instance
    # what should go in the tool.xml? 
        # tool name (tool.id)
        # tool version (tool.version)
        # short descr (tool::description)
        # tool command (tool::command)
        # input name (tool::inputs::param.label)
        # input params (tool::inputs::param::options)
        # output name (tool::outputs::data.label)
        # long descr (tool::help)
        # wrapper license (tool::help)
        # wrappee license (tool::help)
    # what should go in the tool_conf.xml? 
        # tool tag (section.id, section.name)
        # path of tool.xml 
    # stop the image

# create videodb.loc file using storage path specified in config

# download clams-galaxy 
    # inject tool xml files, tool_conf.xml, and vodeodb.loc to proper places
    # build clams-galaxy docker image (--no-cache) 
```

**Comment by marcverhagen** [comment]
A slightly different, but overlapping, issue is what needs to be in the application's metadata and/or the toolshed to make this work.  Most of the things that go into `tool.xml` qualify (but maybe not input and output name). And somewhere the script needs to know where the repositories are. I was first thinking that could be part of the metadata, but I know think that maybe it should be in the toolshed and that the process that creates the toolshed adds the repository URL.

Not sure whether anybody gave some thoughts as to what the toolshed would look like, so I will just throw out some loose thoughts for discussion:

- The toolshed, code and data, is stored in a Github repository and published from there.
- The published toolshed has a URL like https://apps.clams.ai.
- There is an entry for each app (for example https://apps.clams.ai/kaldi).
- There is a sub entry for each version (for example https://apps.clams.ai/kaldi/0.2.4).
- Either the app URL or the version URL is used as an identifier in the app metadata. If it is the former then we also need a version number in the app metadata.
- A toolshed app entry is built automatically from an app repository.
- For each app version the toolshed contains:
  - a link to the GitHub repository for the app and a particular release
  - the Dockerfile
  - a metadata file in JSON or YAML format
  - Docker file and metadata file each have their own URL.
- In the metadata of a MMIF view, our applications refer to the toolshed entry. Third party tools may use some other URI.

It is a bit weird to call this a toolshed because what we put in the shed are app, but appshed sounds like ape shit.

**Comment by keighrim** [comment]
For now, until the app metadata scheme is settle, I added more configurable parameters for apps in the `config.yaml` to generate that `tool.xml` file. Specifically, in additional to `enabled` and `repository`, users can provide `description` for a human-friendly app name (compared to the app names as keys to app objects in the yaml file) and `input` for app categories. (a comma-separated list one or more from `Text`, `Video`, `Audio`, and `Image`)

**Comment by keighrim** [comment]
The prototype maker proved to be working. The app metadata part isn't fully implemented yet, but that will come with development of the app directory, perhaps with many new issue cards. So I'm closing this issue for now.
